# Site settings
title: SLAM Airborne Particle Detection and Surveillance Robot
email: paul@rayes.io
description: > # this means to ignore newlines until "baseurl:"
  Documentation website for SLAM robot senior design project,
  capable of air quality monitoring in cleanrooms.
baseurl: "/slambot" # the subpath of your site, e.g. /blog/
url: "/slambot" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed
